/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    articles: Article;
    categories: Category;
    media: Media;
    penggerak: Penggerak;
    mitra: Mitra;
    video: Video;
    'modul-pelatihan': ModulPelatihan;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    penggerak: PenggerakSelect<false> | PenggerakSelect<true>;
    mitra: MitraSelect<false> | MitraSelect<true>;
    video: VideoSelect<false> | VideoSelect<true>;
    'modul-pelatihan': ModulPelatihanSelect<false> | ModulPelatihanSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en') | ('id' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'id' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Halaman situs yang disusun dari blok. Seret blok untuk mengubah urutannya, lalu pakai Pratinjau untuk melihat hasilnya sebelum diterbitkan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Tambahkan blok sesuai urutan tampilan dari atas ke bawah. Seret untuk mengubah urutan.
   */
  layout?:
    | (
        | {
            /**
             * Setiap slide tampil bergantian otomatis. Untuk satu gambar diam, cukup isi satu slide.
             */
            slides?:
              | {
                  title: string;
                  /**
                   * Bagian akhir judul yang diberi warna kuning, mis. “Bermakna dan Bernalar”. Ditempel setelah judul, jangan diketik ulang di kolom Judul.
                   */
                  highlight?: string | null;
                  description?: string | null;
                  /**
                   * Gambar melintang beresolusi tinggi, minimal 1920 piksel.
                   */
                  image: number | Media;
                  /**
                   * Kosongkan keduanya bila blok ini tidak perlu tombol.
                   */
                  cta?: {
                    label?: string | null;
                    /**
                     * Contoh: /tumbuh-bersama atau https://…
                     */
                    href?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            description?: string | null;
            image: number | Media;
            /**
             * Lapisan warna di atas gambar agar teks tetap terbaca. Pilih Gelap bila gambarnya terang.
             */
            tint?: ('navy' | 'dark') | null;
            garisBawah?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            lebar?: ('sedang' | 'penuh') | null;
            rataTengah?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            /**
             * Di layar ponsel semua blok tetap turun menjadi satu kolom.
             */
            kolom?: ('2' | '3' | '4') | null;
            /**
             * Bila diisi, kartu-kartu bergeser ke kanan dan gambar ini mengisi kolom kiri. Dipakai halaman Mitra.
             */
            gambarSamping?: {
              gambar?: (number | null) | Media;
              judul?: string | null;
              /**
               * Ditempel di depan judul, mis. “Selalu Ada Ruang”.
               */
              judulSorot?: string | null;
            };
            cards?:
              | {
                  judul: string;
                  /**
                   * Baris kecil di bawah judul, mis. kepanjangan singkatan lembaga.
                   */
                  subjudul?: string | null;
                  /**
                   * Boleh memakai daftar bernomor — dipakai kotak Misi di halaman Tentang.
                   */
                  isi?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  /**
                   * Opsional. Tampil di atas judul.
                   */
                  gambar?: (number | null) | Media;
                  warna?: ('putih' | 'abu' | 'navy' | 'merah' | 'kuning') | null;
                  /**
                   * Kosongkan keduanya bila blok ini tidak perlu tombol.
                   */
                  cta?: {
                    label?: string | null;
                    /**
                     * Contoh: /tumbuh-bersama atau https://…
                     */
                    href?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureCards';
          }
        | {
            /**
             * Tampilan beranda: kartu naik menutupi bagian bawah hero. Hanya masuk akal bila blok ini tepat di bawah blok Hero.
             */
            tumpukDiAtasHero?: boolean | null;
            cards?:
              | {
                  title: string;
                  body: string;
                  tone: 'red' | 'navy' | 'yellow';
                  /**
                   * Kosongkan keduanya bila blok ini tidak perlu tombol.
                   */
                  cta?: {
                    label?: string | null;
                    /**
                     * Contoh: /tumbuh-bersama atau https://…
                     */
                    href?: string | null;
                  };
                  /**
                   * Dipakai bila kartu perlu beberapa tautan kecil alih-alih satu tombol.
                   */
                  links?:
                    | {
                        label?: string | null;
                        href?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'valueCards';
          }
        | {
            judul: string;
            isi?: string | null;
            warna?: ('putih' | 'abu' | 'navy' | 'merah' | 'kuning') | null;
            rataTengah?: boolean | null;
            /**
             * Tampil sebagai kotak-kotak persegi di bawah teks. Dipakai bagian “Rangkaian produk pilihan”.
             */
            gambar?: (number | Media)[] | null;
            /**
             * Kosongkan keduanya bila blok ini tidak perlu tombol.
             */
            cta?: {
              label?: string | null;
              /**
               * Contoh: /tumbuh-bersama atau https://…
               */
              href?: string | null;
            };
            /**
             * Tampil sebagai pil putih berjajar, mis. “Shopee” dan “Tokopedia”.
             */
            tautanTambahan?:
              | {
                  /**
                   * Mis. “Temukan Kami:”. Cukup diisi pada tautan pertama.
                   */
                  awalan?: string | null;
                  label: string;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            title: string;
            body?: string | null;
            image?: (number | null) | Media;
            /**
             * Kosongkan keduanya bila blok ini tidak perlu tombol.
             */
            cta?: {
              label?: string | null;
              /**
               * Contoh: /tumbuh-bersama atau https://…
               */
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            heading?: string | null;
            /**
             * Urutan di sini menentukan urutan dari atas ke bawah. Entri tampil berselang-seling kiri dan kanan secara otomatis.
             */
            entries?:
              | {
                  /**
                   * Mis. 2018
                   */
                  tahun: string;
                  teks: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            heading?: string | null;
            stats?:
              | {
                  /**
                   * Angka saja, tanpa titik/koma. Mis. 16000
                   */
                  value: number;
                  /**
                   * Mis. “+” atau “ribu”. Boleh dikosongkan.
                   */
                  suffix?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statCounter';
          }
        | {
            heading?: string | null;
            /**
             * Artikel terbaru diambil lebih dulu.
             */
            limit?: number | null;
            /**
             * Di layar ponsel semua blok tetap turun menjadi satu kolom.
             */
            kolom?: ('2' | '3' | '4') | null;
            /**
             * Kosongkan untuk menampilkan semua kategori.
             */
            category?: (number | null) | Category;
            /**
             * Kosongkan keduanya bila blok ini tidak perlu tombol.
             */
            cta?: {
              label?: string | null;
              /**
               * Contoh: /tumbuh-bersama atau https://…
               */
              href?: string | null;
            };
            /**
             * Membuat bagian ini bisa dituju langsung lewat alamat, mis. “/#kabar-terbaru”. Hanya huruf kecil dan tanda hubung. Jangan diubah bila sudah dipakai di menu.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latestNews';
          }
        | {
            /**
             * Blok ini menampilkan seluruh isi Data Situs → Penggerak, urut menurut “Urutan tampil”. Untuk menambah atau menghapus orang, sunting koleksinya — bukan blok ini.
             */
            heading?: string | null;
            /**
             * Membuat bagian ini bisa dituju langsung lewat alamat, mis. “/tentang-gernas-tastaka#penggerak”. Hanya huruf kecil dan tanda hubung. Jangan diubah bila sudah dipakai di menu.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamGrid';
          }
        | {
            /**
             * Logo diambil dari Data Situs → Mitra. Tambah atau ganti logo di koleksi itu, bukan di sini.
             */
            heading?: string | null;
            /**
             * “Berkelompok” menampilkan semua mitra di bawah judul kelompoknya masing-masing. “Barisan berjalan” hanya menampilkan mitra yang dicentang “Tampilkan di beranda”.
             */
            tampilan: 'berkelompok' | 'barisan';
            /**
             * Kosongkan keduanya bila blok ini tidak perlu tombol.
             */
            cta?: {
              label?: string | null;
              /**
               * Contoh: /tumbuh-bersama atau https://…
               */
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnerLogos';
          }
        | {
            /**
             * Video diambil dari Data Situs → Video, urut menurut “Urutan tampil”.
             */
            heading?: string | null;
            /**
             * Kosongkan untuk menampilkan semua video.
             */
            limit?: number | null;
            /**
             * Di layar ponsel semua blok tetap turun menjadi satu kolom.
             */
            kolom?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoGrid';
          }
        | {
            /**
             * Modul diambil dari Data Situs → Modul Pelatihan. Warna kartu berganti merah–biru–kuning otomatis mengikuti urutan.
             */
            heading?: string | null;
            program: 'matematika' | 'membaca';
            /**
             * Halaman Belajar Bersama memakai keduanya: “Ringkas” di bagian Topik Pelatihan, “Rincian” di bagian Rincian Modul.
             */
            tampilan: 'topik' | 'rincian';
            /**
             * Hanya tampil pada tampilan Ringkas. Kosongkan judul untuk menyembunyikannya.
             */
            sidebar?: {
              teks?: string | null;
              /**
               * Mis. “Tertarik untuk belajar?”
               */
              ajakan?: string | null;
              /**
               * Kosongkan keduanya bila blok ini tidak perlu tombol.
               */
              cta?: {
                label?: string | null;
                /**
                 * Contoh: /tumbuh-bersama atau https://…
                 */
                href?: string | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'trainingModules';
          }
        | {
            heading?: string | null;
            /**
             * Foto boleh beda ukuran — tingginya menyesuaikan sendiri. Seret untuk mengubah urutan.
             */
            images: (number | Media)[];
            /**
             * Di layar ponsel semua blok tetap turun menjadi satu kolom.
             */
            kolom?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            /**
             * Warna latar tiap kutipan berganti kuning–biru–merah otomatis mengikuti urutan.
             */
            items?:
              | {
                  kutipan: string;
                  nama: string;
                  /**
                   * Mis. “Guru SDN 10 Lahat”.
                   */
                  peran?: string | null;
                  foto?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            /**
             * Peta sebaran provinsi sudah tertanam di situs dan tidak disunting dari sini.
             */
            tampilkanPeta?: boolean | null;
            stats?:
              | {
                  /**
                   * Angka saja, tanpa titik/koma. Mis. 16000
                   */
                  value: number;
                  /**
                   * Mis. “+” atau “ribu”. Boleh dikosongkan.
                   */
                  suffix?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'indonesiaMap';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  judul: string;
                  /**
                   * Mis. “Kelas 1”. Tampil sebagai label kuning.
                   */
                  kelas?: string | null;
                  /**
                   * Mis. “Bilangan” atau “Fonik”. Tampil sebagai label merah.
                   */
                  topik?: string | null;
                  gambar: number | Media;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Di layar ponsel semua blok tetap turun menjadi satu kolom.
             */
            kolom?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ideaCards';
          }
        | {
            /**
             * Isian formulirnya tetap (nama, surel, pesan) dan tidak diubah dari sini.
             */
            heading?: string | null;
            /**
             * Membuat bagian ini bisa dituju langsung lewat alamat, mis. “/mitra#hubungi”. Hanya huruf kecil dan tanda hubung. Jangan diubah bila sudah dipakai di menu.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            judul: string;
            /**
             * Ditempel di akhir judul, mis. “Bernalar”.
             */
            judulSorot?: string | null;
            isi?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'donationTiers';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  judul: string;
                  gambar: number | Media;
                  /**
                   * Angka saja, tanpa titik. Mis. 270000000
                   */
                  terkumpul: number;
                  target: number;
                  /**
                   * Kosongkan keduanya bila blok ini tidak perlu tombol.
                   */
                  cta?: {
                    label?: string | null;
                    /**
                     * Contoh: /tumbuh-bersama atau https://…
                     */
                    href?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Di layar ponsel semua blok tetap turun menjadi satu kolom.
             */
            kolom?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'donationCampaigns';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * Bagian akhir alamat halaman. Dibuat otomatis dari judul — ubah hanya bila perlu menyamakan dengan URL lama.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Deskripsi singkat gambar untuk pembaca layar & SEO. Kosongkan bila gambar murni dekoratif.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Lokasi berkas ini di situs WordPress lama. Dipakai untuk memetakan gambar ke artikel saat migrasi, dan sebagai penanda agar impor tidak terduplikasi. Kosong untuk unggahan baru.
   */
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Bagian akhir alamat halaman. Dibuat otomatis dari judul — ubah hanya bila perlu menyamakan dengan URL lama.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Berita dan kabar terbaru. Tampil di halaman Publikasi dan pada blok “Berita Terbaru” di halaman mana pun yang memakainya.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  image?: (number | null) | Media;
  /**
   * Cuplikan singkat di kartu berita. Bila kosong, diambil dari paragraf pertama.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * Bagian akhir alamat halaman. Dibuat otomatis dari judul — ubah hanya bila perlu menyamakan dengan URL lama.
   */
  slug: string;
  publishedAt: string;
  category?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Daftar penggerak yang tampil pada blok “Penggerak”. Menambah orang di sini otomatis menambahkannya di halaman yang memakai blok itu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "penggerak".
 */
export interface Penggerak {
  id: number;
  nama: string;
  /**
   * Sebaiknya foto potret persegi. Bila kosong, kotak abu-abu yang tampil.
   */
  foto?: (number | null) | Media;
  /**
   * Satu baris per jabatan. Semuanya tampil dipisah tanda titik tengah, mis. “Trainer Gernas Tastaka · Peneliti PRPIC”.
   */
  peran?:
    | {
        nama: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Angka kecil tampil lebih dulu. Biarkan 100 bila urutannya tidak penting.
   */
  urutan?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logo mitra. Dipakai blok “Logo Mitra” di halaman Mitra (dikelompokkan) dan di beranda (barisan berjalan).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mitra".
 */
export interface Mitra {
  id: number;
  /**
   * Dipakai sebagai teks alternatif logo, jadi tetap isi walau logonya sudah memuat nama.
   */
  nama: string;
  /**
   * Sebaiknya PNG berlatar transparan.
   */
  logo: number | Media;
  /**
   * Menentukan di bawah judul mana logo ini dikelompokkan.
   */
  kelompok: 'pemerintah' | 'korporasi' | 'pendidikan';
  /**
   * Bila dicentang, logo ikut pada barisan mitra yang berjalan di beranda.
   */
  tampilDiBeranda?: boolean | null;
  /**
   * Angka kecil tampil lebih dulu. Biarkan 100 bila urutannya tidak penting.
   */
  urutan?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Daftar video. Dipakai blok “Daftar Video”; blok itu bisa dibatasi jumlahnya, mis. hanya 3 teratas di beranda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video".
 */
export interface Video {
  id: number;
  judul: string;
  /**
   * Gambar yang tampil sebelum video diklik. Sebaiknya melintang (16:9).
   */
  thumbnail: number | Media;
  /**
   * Alamat lengkap video, mis. https://www.youtube.com/watch?v=… . Bila kosong, sampulnya tetap tampil tetapi tidak bisa diklik.
   */
  tautan?: string | null;
  /**
   * Angka kecil tampil lebih dulu. Biarkan 100 bila urutannya tidak penting.
   */
  urutan?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Modul pelatihan matematika & membaca. Dipakai blok “Modul Pelatihan” di halaman Belajar Bersama.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modul-pelatihan".
 */
export interface ModulPelatihan {
  id: number;
  /**
   * Mis. “Bilangan” atau “Prinsip-Prinsip Dasar Mengajar”.
   */
  judul: string;
  /**
   * Menentukan bagian mana di halaman yang memuat modul ini.
   */
  program: 'matematika' | 'membaca';
  /**
   * Angka yang tampil sebagai “Pelatihan 1”, “Pelatihan 2”, dan seterusnya.
   */
  nomor: number;
  /**
   * Poin-poin yang tampil pada kartu rincian modul. Satu baris per tujuan.
   */
  tujuan?:
    | {
        teks: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Angka kecil tampil lebih dulu. Biarkan 100 bila urutannya tidak penting.
   */
  urutan?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admin dapat mengelola pengguna lain. Editor hanya mengelola konten.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'penggerak';
        value: number | Penggerak;
      } | null)
    | ({
        relationTo: 'mitra';
        value: number | Mitra;
      } | null)
    | ({
        relationTo: 'video';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'modul-pelatihan';
        value: number | ModulPelatihan;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              slides?:
                | T
                | {
                    title?: T;
                    highlight?: T;
                    description?: T;
                    image?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageHero?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              tint?: T;
              garisBawah?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              content?: T;
              lebar?: T;
              rataTengah?: T;
              id?: T;
              blockName?: T;
            };
        featureCards?:
          | T
          | {
              heading?: T;
              kolom?: T;
              gambarSamping?:
                | T
                | {
                    gambar?: T;
                    judul?: T;
                    judulSorot?: T;
                  };
              cards?:
                | T
                | {
                    judul?: T;
                    subjudul?: T;
                    isi?: T;
                    gambar?: T;
                    warna?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        valueCards?:
          | T
          | {
              tumpukDiAtasHero?: T;
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    tone?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    links?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              judul?: T;
              isi?: T;
              warna?: T;
              rataTengah?: T;
              gambar?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              tautanTambahan?:
                | T
                | {
                    awalan?: T;
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              title?: T;
              body?: T;
              image?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              heading?: T;
              entries?:
                | T
                | {
                    tahun?: T;
                    teks?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statCounter?:
          | T
          | {
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        latestNews?:
          | T
          | {
              heading?: T;
              limit?: T;
              kolom?: T;
              category?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        teamGrid?:
          | T
          | {
              heading?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        partnerLogos?:
          | T
          | {
              heading?: T;
              tampilan?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoGrid?:
          | T
          | {
              heading?: T;
              limit?: T;
              kolom?: T;
              id?: T;
              blockName?: T;
            };
        trainingModules?:
          | T
          | {
              heading?: T;
              program?: T;
              tampilan?: T;
              sidebar?:
                | T
                | {
                    teks?: T;
                    ajakan?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              kolom?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    kutipan?: T;
                    nama?: T;
                    peran?: T;
                    foto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        indonesiaMap?:
          | T
          | {
              heading?: T;
              tampilkanPeta?: T;
              stats?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ideaCards?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    judul?: T;
                    kelas?: T;
                    topik?: T;
                    gambar?: T;
                    href?: T;
                    id?: T;
                  };
              kolom?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        donationTiers?:
          | T
          | {
              judul?: T;
              judulSorot?: T;
              isi?: T;
              id?: T;
              blockName?: T;
            };
        donationCampaigns?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    judul?: T;
                    gambar?: T;
                    terkumpul?: T;
                    target?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                  };
              kolom?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  excerpt?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  publishedAt?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "penggerak_select".
 */
export interface PenggerakSelect<T extends boolean = true> {
  nama?: T;
  foto?: T;
  peran?:
    | T
    | {
        nama?: T;
        id?: T;
      };
  urutan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mitra_select".
 */
export interface MitraSelect<T extends boolean = true> {
  nama?: T;
  logo?: T;
  kelompok?: T;
  tampilDiBeranda?: T;
  urutan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video_select".
 */
export interface VideoSelect<T extends boolean = true> {
  judul?: T;
  thumbnail?: T;
  tautan?: T;
  urutan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modul-pelatihan_select".
 */
export interface ModulPelatihanSelect<T extends boolean = true> {
  judul?: T;
  program?: T;
  nomor?: T;
  tujuan?:
    | T
    | {
        teks?: T;
        id?: T;
      };
  urutan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  social?:
    | {
        platform?: ('instagram' | 'facebook' | 'youtube' | 'x' | 'linkedin' | 'tiktok') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  address?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}